name: Build HTML mínimo (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install python-dateutil

      - name: Build minimal HTML
        run: python scripts/make_html_min.py
              - name: List tree after build
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "----"
          ls -la daily || true
          echo "----"
          find daily -maxdepth 3 -type f -name "*.html" -print || true

      - name: Git status (qué se va a commitear)
        run: |
          git status

      - name: Commit HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily/**/*.html || true
          git commit -m "chore: build minimal HTML" || echo "No changes"
          git push
